server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: root

# Optional: If you're using JPA
spring.jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
